<x-app-layout>

    {{-- Header image --}}
    <div class="h-screen p-10 flex items-center w-full z-40" style="background: url('../images/piano-background.jpg'); background-repeat: no-repeat; background-size: cover;">
        <div class="text-white">
            <p class="text-5xl">"El problema no está en ilusionarse, <br> el problema está en ver la realidad."</p><br>
            <span class="text-2xl">- El pianista</span>
        </div>
    </div>    

    {{-- Content --}}
    <div class="bg-white mx-3 md:mx-10 p-3 md:p-10">
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p><br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima,olor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recLorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p><br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima,olor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p><br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima,olor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recLorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p><br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima,olor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p><br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima,olor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recLorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p><br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima,olor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p><br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima,olor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recLorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p><br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima,olor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p><br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima,olor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recLorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p><br>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima,olor, sit amet consectetur adipisicing elit. Eveniet inventore quis enim architecto! Voluptates velit beatae, explicabo, ad et qui expedita eligendi minima, voluptas molestiae adipisci recusandae repellat autem eum!</p>
    </div>
</x-app-layout>